name: Improved Terraform Workflow

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    name: Lint and Validate Terraform Code
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"

      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint
        with:
          tflint_version: v0.52.0

      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          path: ~/.tflint.d/plugins

      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


      - name: terraform init
        run: terraform init
        
      - name: Run Terraform Fmt Check
        run: terraform fmt -recursive
        continue-on-error: true


      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init
        env:
          # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        run: tflint -f compact


      - name: Run Terraform Validate
        run: terraform validate

      - name: Install tflint
        run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Run tflint
        run: tflint

  plan:
    name: Plan Infrastructure Changes
    runs-on: ubuntu-latest
    environment: testing
    needs: lint
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

  apply:
    name: Apply Infrastructure Changes
    runs-on: ubuntu-latest
    environment: testing
    needs: plan
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"

      - name: Terraform Apply
        run: terraform apply -auto-approve
