name: Improved Terraform Workflow

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    name: Lint and Validate Terraform Code
    runs-on: ubuntu-latest
    environment: testing
    steps:
      # Step 1: Checkout Repository
      - name: Clone Repository
        uses: actions/checkout@v4

      # Step 2: Azure Login 
      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 3: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"

      # # Step 4: Run Terraform Fmt Check
      # - name: Run Terraform Fmt Check
      #   run: terraform fmt -recursive -check
      #   continue-on-error: true

      # Step 5: Run Terraform Validate
      - name: Run Terraform Validate
        run: terraform validate

      # # Step 6: Setup TFLint
      # - name: Setup TFLint
      #   uses: terraform-linters/setup-tflint@v4
      #   with:
      #     tflint_version: v0.52.0

      # Step 7: Init TFLint Plugins
      # - name: Init TFLint Plugins
      #   run: tflint --init
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Prevent rate limiting

      # # Step 8: Run TFLint
      # - name: Run TFLint
      #   run: tflint -f compact
       




