name: issues

on: push

permissions:
  id-token: write
  contents: read

jobs:
  issues:
    runs-on: ubuntu-latest
    steps:
      - name: dump github context
        run: echo "{{ toJSON(github.event }}"
